-- Autogenerated dump of public schema (tables/views/indexes/functions).
-- Generated: 2026-08-12T23:42:52.861Z
-- Source: live Supabase via scripts/dump-schema.mjs
-- This file is documentation; apply changes via supabase/migrations/*.sql

-- Objects
-- TABLE public.alert_configs
-- TABLE public.alerts
-- TABLE public.api_subscribers
-- TABLE public.app_profiles
-- TABLE public.case_stories
-- TABLE public.checkout_sessions
-- TABLE public.data_quality_reviews
-- TABLE public.entities
-- TABLE public.entitlements
-- TABLE public.entity_aliases
-- TABLE public.entity_watchlist_members
-- TABLE public.entity_watchlists
-- TABLE public.event_evidence
-- TABLE public.event_news_coverage
-- TABLE public.friction_score_history
-- TABLE public.friction_scores
-- TABLE public.ghost_employers
-- TABLE public.ghost_wall_posts
-- TABLE public.ingest_runs
-- TABLE public.legal_events
-- TABLE public.map_cross_signals
-- TABLE public.map_signal_locations
-- TABLE public.market_events
-- TABLE public.markets
-- TABLE public.paper_predictions
-- TABLE public.profiles
-- TABLE public.query_audit_events
-- TABLE public.raw_records
-- TABLE public.read_audit_events
-- TABLE public.sales_leads
-- TABLE public.search_term_signals
-- TABLE public.service_requests
-- TABLE public.source_catalog
-- TABLE public.waitlist_signups
-- TABLE public.watchlist_alert_deliveries
-- TABLE public.watchlist_entities
-- TABLE public.watchlists
-- VIEW public.companies
-- VIEW public.ghost_leaderboard_v
-- VIEW public.signals

-- TABLE public.alert_configs
-- create table public.alert_configs (
--   id uuid not null default gen_random_uuid(),
--   owner_email citext not null,
--   watchlist_id uuid null,
--   record_types jsonb not null default '[]'::jsonb,
--   threshold integer not null default 70,
--   channels jsonb not null default '["email"]'::jsonb,
--   enabled boolean not null default true,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.alerts
-- create table public.alerts (
--   id uuid not null default gen_random_uuid(),
--   watchlist_id uuid null,
--   entity_id uuid null,
--   event_id uuid null,
--   channel text not null default 'email'::text,
--   status text not null default 'queued'::text,
--   message text not null,
--   sent_at timestamp with time zone null,
--   created_at timestamp with time zone not null default now(),
-- );

-- TABLE public.api_subscribers
-- create table public.api_subscribers (
--   id uuid not null default gen_random_uuid(),
--   owner_email citext not null,
--   plan text not null,
--   token_hash text not null,
--   status text not null default 'active'::text,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.app_profiles
-- create table public.app_profiles (
--   user_id uuid not null,
--   email citext not null,
--   role text not null default 'customer'::text,
--   plan text null,
--   subscription_status text not null default 'none'::text,
--   stripe_customer_id text null,
--   stripe_subscription_id text null,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.case_stories
-- create table public.case_stories (
--   id uuid not null default gen_random_uuid(),
--   slug text not null,
--   status text not null default 'pending_review'::text,
--   headline text not null,
--   dek text null,
--   body text not null,
--   video_script text null,
--   record_type text null,
--   event_id uuid null,
--   entity_id uuid null,
--   source_fields jsonb not null default '{}'::jsonb,
--   model text null,
--   generation_notes jsonb not null default '[]'::jsonb,
--   reviewed_by text null,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
--   published_at timestamp with time zone null,
-- );

-- TABLE public.checkout_sessions
-- create table public.checkout_sessions (
--   id uuid not null default gen_random_uuid(),
--   stripe_session_id text null,
--   plan text not null,
--   price_id text not null,
--   mode text not null,
--   status text not null default 'created'::text,
--   email text null,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.companies
-- create table public.companies (
--   id uuid null,
--   name text null,
--   entity_type text null,
--   jurisdiction text null,
--   ticker text null,
--   status text null,
--   created_at timestamp with time zone null,
--   updated_at timestamp with time zone null,
-- );

-- TABLE public.data_quality_reviews
-- create table public.data_quality_reviews (
--   id uuid not null default gen_random_uuid(),
--   event_id uuid null,
--   issue_type text not null,
--   note text not null default ''::text,
--   status text not null default 'open'::text,
--   created_by citext null,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.entities
-- create table public.entities (
--   id uuid not null default gen_random_uuid(),
--   canonical_name text not null,
--   entity_type text not null default 'company'::text,
--   ticker text null,
--   jurisdiction text null,
--   registered_agent text null,
--   primary_address text null,
--   website text null,
--   status text not null default 'active'::text,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
--   normalized_name text null,
--   cik text null,
-- );

-- TABLE public.entitlements
-- create table public.entitlements (
--   id uuid not null default gen_random_uuid(),
--   plan text not null,
--   label text not null,
--   monthly_price text null,
--   search_limit integer null,
--   watchlist_limit integer null,
--   alert_limit integer null,
--   features jsonb not null default '[]'::jsonb,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.entity_aliases
-- create table public.entity_aliases (
--   id uuid not null default gen_random_uuid(),
--   entity_id uuid not null,
--   alias text not null,
--   alias_type text not null default 'name'::text,
--   confidence numeric not null default 100,
--   created_at timestamp with time zone not null default now(),
--   normalized_alias text null,
--   source text null,
-- );

-- TABLE public.entity_watchlist_members
-- create table public.entity_watchlist_members (
--   watchlist_id uuid not null,
--   entity_id uuid not null,
--   created_at timestamp with time zone not null default now(),
-- );

-- TABLE public.entity_watchlists
-- create table public.entity_watchlists (
--   id uuid not null default gen_random_uuid(),
--   user_id uuid not null,
--   label text not null,
--   entity_ids ARRAY not null default '{}'::uuid[],
--   source text not null default 'manual'::text,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.event_evidence
-- create table public.event_evidence (
--   id uuid not null default gen_random_uuid(),
--   event_id uuid not null,
--   source_url text not null,
--   document_id text null,
--   evidence_type text not null default 'source_link'::text,
--   retrieved_at timestamp with time zone not null default now(),
--   metadata jsonb not null default '{}'::jsonb,
-- );

-- TABLE public.event_news_coverage
-- create table public.event_news_coverage (
--   event_id uuid not null,
--   detected_at timestamp with time zone not null,
--   news_mentioned_at timestamp with time zone not null,
--   coverage_source text not null default 'rss'::text,
--   coverage_title text null,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.friction_score_history
-- create table public.friction_score_history (
--   id uuid not null default gen_random_uuid(),
--   entity_id uuid not null,
--   score integer not null,
--   confidence integer not null,
--   trend text null,
--   reasons jsonb not null default '[]'::jsonb,
--   category_scores jsonb not null default '{}'::jsonb,
--   model_version text null,
--   computed_at timestamp with time zone not null default now(),
--   recorded_at timestamp with time zone not null default now(),
-- );

-- TABLE public.friction_scores
-- create table public.friction_scores (
--   id uuid not null default gen_random_uuid(),
--   entity_id uuid not null,
--   score integer not null,
--   confidence integer not null,
--   trend text not null default 'flat'::text,
--   reasons jsonb not null default '[]'::jsonb,
--   category_scores jsonb not null default '{}'::jsonb,
--   model_version text not null default 'friction-v1'::text,
--   computed_at timestamp with time zone not null default now(),
-- );

-- TABLE public.ghost_employers
-- create table public.ghost_employers (
--   slug text not null,
--   display_label text not null,
--   approx_headcount integer not null,
--   created_at timestamp with time zone not null default now(),
-- );

-- TABLE public.ghost_leaderboard_v
-- create table public.ghost_leaderboard_v (
--   employer_slug text null,
--   display_label text null,
--   approx_headcount integer null,
--   report_count bigint null,
--   last_report_at timestamp with time zone null,
-- );

-- TABLE public.ghost_wall_posts
-- create table public.ghost_wall_posts (
--   id uuid not null default gen_random_uuid(),
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
--   caption text null,
--   storage_path text not null,
--   user_certified boolean not null default false,
--   status text not null default 'pending'::text,
--   moderation_notes text null,
--   employer_slug text null,
--   user_id uuid null,
-- );

-- TABLE public.ingest_runs
-- create table public.ingest_runs (
--   id uuid not null default gen_random_uuid(),
--   source_id uuid null,
--   adapter text not null,
--   status text not null,
--   started_at timestamp with time zone not null default now(),
--   finished_at timestamp with time zone null,
--   fetched_count integer not null default 0,
--   normalized_count integer not null default 0,
--   error text null,
--   checksum text null,
--   metadata jsonb not null default '{}'::jsonb,
-- );

-- TABLE public.legal_events
-- create table public.legal_events (
--   id uuid not null default gen_random_uuid(),
--   entity_id uuid not null,
--   source_id uuid null,
--   raw_record_id uuid null,
--   event_type text not null,
--   title text not null,
--   summary text not null,
--   jurisdiction text not null,
--   filing_date date not null,
--   amount numeric null,
--   severity integer not null default 50,
--   confidence numeric not null default 80,
--   status text not null default 'open'::text,
--   allegation_disclaimer text not null default 'This record is an allegation or administrative filing, not a judgment.'::text,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
--   trade_date date null,
-- );

-- TABLE public.map_cross_signals
-- create table public.map_cross_signals (
--   id uuid not null,
--   trade_event_id uuid not null,
--   distress_event_id uuid not null,
--   trade_entity_id uuid not null,
--   distress_entity_id uuid not null,
--   correlation_key_type text not null,
--   ticker text null,
--   trade_event_type text not null,
--   distress_event_type text not null,
--   trade_date date not null,
--   distress_date date not null,
--   days_between integer not null,
--   longitude double precision not null,
--   latitude double precision not null,
--   location_confidence text not null,
--   location_precision text not null,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.map_signal_locations
-- create table public.map_signal_locations (
--   event_id uuid not null,
--   entity_id uuid not null,
--   event_type text not null,
--   signal_group text not null,
--   filing_date date not null,
--   longitude double precision null,
--   latitude double precision null,
--   location_label text not null default ''::text,
--   geocoding_confidence text not null default 'unresolved'::text,
--   location_precision text not null default 'unknown'::text,
--   geocoder text not null default 'unresolved'::text,
--   matched_address text null,
--   geocoder_match_type text null,
--   review_reason text null,
--   source_fields jsonb not null default '{}'::jsonb,
--   attempted_at timestamp with time zone not null default now(),
--   geocoded_at timestamp with time zone null,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.market_events
-- create table public.market_events (
--   id uuid not null default gen_random_uuid(),
--   market_id uuid null,
--   event_type text not null,
--   probability numeric null,
--   source_url text null,
--   summary text not null,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamp with time zone not null default now(),
-- );

-- TABLE public.markets
-- create table public.markets (
--   id uuid not null default gen_random_uuid(),
--   slug text null,
--   title text not null,
--   description text null,
--   yes_price numeric null,
--   outcome text null default 'open'::text,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
--   source_url text null,
--   closes_at timestamp with time zone null,
-- );

-- TABLE public.paper_predictions
-- create table public.paper_predictions (
--   id uuid not null default gen_random_uuid(),
--   user_id uuid not null,
--   market_id uuid not null,
--   side text not null,
--   probability numeric null,
--   resolved boolean not null default false,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.profiles
-- create table public.profiles (
--   id uuid not null,
--   email citext null,
--   display_name text null,
--   tier text not null default 'free'::text,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.query_audit_events
-- create table public.query_audit_events (
--   id uuid not null default gen_random_uuid(),
--   subscriber_email citext null,
--   surface text not null,
--   query jsonb not null default '{}'::jsonb,
--   result_count integer not null default 0,
--   created_at timestamp with time zone not null default now(),
-- );

-- TABLE public.raw_records
-- create table public.raw_records (
--   id uuid not null default gen_random_uuid(),
--   source_id uuid null,
--   ingest_run_id uuid null,
--   source_record_id text null,
--   payload_hash text not null,
--   fetched_url text null,
--   source_timestamp timestamp with time zone null,
--   retrieved_at timestamp with time zone not null default now(),
--   normalized_status text not null default 'pending'::text,
--   payload jsonb not null default '{}'::jsonb,
-- );

-- TABLE public.read_audit_events
-- create table public.read_audit_events (
--   id uuid not null default gen_random_uuid(),
--   subscriber_email citext null,
--   surface text not null,
--   entity_id uuid null,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamp with time zone not null default now(),
-- );

-- TABLE public.sales_leads
-- create table public.sales_leads (
--   id uuid not null default gen_random_uuid(),
--   email citext not null,
--   name text not null,
--   company text not null,
--   use_case text not null,
--   message text not null default ''::text,
--   source text not null default 'website'::text,
--   status text not null default 'new'::text,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.search_term_signals
-- create table public.search_term_signals (
--   id uuid not null default gen_random_uuid(),
--   source_id uuid null,
--   term text not null,
--   jurisdiction text not null,
--   window_start date not null,
--   window_end date not null,
--   current_count integer not null default 0,
--   baseline_count integer not null default 0,
--   surge_ratio numeric not null default 0,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamp with time zone not null default now(),
-- );

-- TABLE public.service_requests
-- create table public.service_requests (
--   id uuid not null default gen_random_uuid(),
--   owner_email citext not null,
--   request_type text not null,
--   subject text not null,
--   details text not null default ''::text,
--   plan text null,
--   priority text not null default 'normal'::text,
--   status text not null default 'queued'::text,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.signals
-- create table public.signals (
--   id uuid null,
--   company_id uuid null,
--   source_id uuid null,
--   record_type text null,
--   title text null,
--   summary text null,
--   jurisdiction text null,
--   filing_date date null,
--   score integer null,
--   confidence numeric null,
--   status text null,
--   created_at timestamp with time zone null,
--   updated_at timestamp with time zone null,
-- );

-- TABLE public.source_catalog
-- create table public.source_catalog (
--   id uuid not null default gen_random_uuid(),
--   slug text not null,
--   name text not null,
--   jurisdiction text not null,
--   record_type text not null,
--   access_method text not null,
--   terms_status text not null default 'needs_review'::text,
--   refresh_cadence text not null default 'daily'::text,
--   source_url text null,
--   enabled boolean not null default false,
--   notes text null,
--   last_success_at timestamp with time zone null,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
--   adapter_kind text not null default 'manual'::text,
--   rate_limit_per_hour integer not null default 60,
--   auth_env_var text null,
--   terms_reviewed_at timestamp with time zone null,
--   disabled_reason text null,
--   config jsonb not null default '{}'::jsonb,
-- );

-- TABLE public.waitlist_signups
-- create table public.waitlist_signups (
--   id uuid not null default gen_random_uuid(),
--   email citext not null,
--   source text not null default 'site'::text,
--   status text not null default 'new'::text,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamp with time zone not null default now(),
--   updated_at timestamp with time zone not null default now(),
-- );

-- TABLE public.watchlist_alert_deliveries
-- create table public.watchlist_alert_deliveries (
--   id uuid not null default gen_random_uuid(),
--   user_id uuid not null,
--   entity_id uuid not null,
--   event_id uuid not null,
--   email text null,
--   plan text null,
--   created_at timestamp with time zone not null default now(),
-- );

-- TABLE public.watchlist_entities
-- create table public.watchlist_entities (
--   id uuid not null default gen_random_uuid(),
--   watchlist_id uuid not null,
--   entity_id uuid null,
--   query text null,
--   created_at timestamp with time zone not null default now(),
-- );

-- TABLE public.watchlists
-- create table public.watchlists (
--   id uuid not null default gen_random_uuid(),
--   user_id uuid not null,
--   market_id uuid not null,
--   created_at timestamp with time zone not null default now(),
-- );

-- Constraints
-- CHECK alert_configs.2200_18742_1_not_null
-- CHECK alert_configs.2200_18742_2_not_null
-- CHECK alert_configs.2200_18742_4_not_null
-- CHECK alert_configs.2200_18742_5_not_null
-- CHECK alert_configs.2200_18742_6_not_null
-- CHECK alert_configs.2200_18742_7_not_null
-- CHECK alert_configs.2200_18742_8_not_null
-- CHECK alert_configs.2200_18742_9_not_null
-- PRIMARY KEY alert_configs.alert_configs_pkey (id) -> alert_configs.id
-- CHECK alert_configs.alert_configs_threshold_check -> alert_configs.threshold
-- FOREIGN KEY alert_configs.alert_configs_watchlist_id_fkey (watchlist_id) -> watchlists.id
-- CHECK alerts.2200_18455_1_not_null
-- CHECK alerts.2200_18455_5_not_null
-- CHECK alerts.2200_18455_6_not_null
-- CHECK alerts.2200_18455_7_not_null
-- CHECK alerts.2200_18455_9_not_null
-- CHECK alerts.alerts_channel_check -> alerts.channel
-- FOREIGN KEY alerts.alerts_entity_id_fkey (entity_id) -> entities.id
-- FOREIGN KEY alerts.alerts_event_id_fkey (event_id) -> legal_events.id
-- PRIMARY KEY alerts.alerts_pkey (id) -> alerts.id
-- CHECK alerts.alerts_status_check -> alerts.status
-- FOREIGN KEY alerts.alerts_watchlist_id_fkey (watchlist_id) -> watchlists.id
-- CHECK api_subscribers.2200_18409_1_not_null
-- CHECK api_subscribers.2200_18409_2_not_null
-- CHECK api_subscribers.2200_18409_3_not_null
-- CHECK api_subscribers.2200_18409_4_not_null
-- CHECK api_subscribers.2200_18409_5_not_null
-- CHECK api_subscribers.2200_18409_6_not_null
-- CHECK api_subscribers.2200_18409_7_not_null
-- UNIQUE api_subscribers.api_subscribers_owner_email_key (owner_email) -> api_subscribers.owner_email
-- PRIMARY KEY api_subscribers.api_subscribers_pkey (id) -> api_subscribers.id
-- FOREIGN KEY api_subscribers.api_subscribers_plan_fkey (plan) -> entitlements.plan
-- CHECK api_subscribers.api_subscribers_status_check -> api_subscribers.status
-- UNIQUE api_subscribers.api_subscribers_token_hash_key (token_hash) -> api_subscribers.token_hash
-- CHECK app_profiles.2200_18574_1_not_null
-- CHECK app_profiles.2200_18574_2_not_null
-- CHECK app_profiles.2200_18574_3_not_null
-- CHECK app_profiles.2200_18574_5_not_null
-- CHECK app_profiles.2200_18574_8_not_null
-- CHECK app_profiles.2200_18574_9_not_null
-- UNIQUE app_profiles.app_profiles_email_key (email) -> app_profiles.email
-- PRIMARY KEY app_profiles.app_profiles_pkey (user_id) -> app_profiles.user_id
-- FOREIGN KEY app_profiles.app_profiles_plan_fkey (plan) -> entitlements.plan
-- CHECK app_profiles.app_profiles_role_check -> app_profiles.role
-- CHECK app_profiles.app_profiles_subscription_status_check -> app_profiles.subscription_status
-- FOREIGN KEY app_profiles.app_profiles_user_id_fkey (user_id)
-- CHECK case_stories.2200_25385_11_not_null
-- CHECK case_stories.2200_25385_13_not_null
-- CHECK case_stories.2200_25385_15_not_null
-- CHECK case_stories.2200_25385_16_not_null
-- CHECK case_stories.2200_25385_1_not_null
-- CHECK case_stories.2200_25385_2_not_null
-- CHECK case_stories.2200_25385_3_not_null
-- CHECK case_stories.2200_25385_4_not_null
-- CHECK case_stories.2200_25385_6_not_null
-- FOREIGN KEY case_stories.case_stories_event_id_fkey (event_id) -> legal_events.id
-- PRIMARY KEY case_stories.case_stories_pkey (id) -> case_stories.id
-- UNIQUE case_stories.case_stories_slug_key (slug) -> case_stories.slug
-- CHECK case_stories.case_stories_status_check -> case_stories.status
-- CHECK checkout_sessions.2200_17777_10_not_null
-- CHECK checkout_sessions.2200_17777_1_not_null
-- CHECK checkout_sessions.2200_17777_3_not_null
-- CHECK checkout_sessions.2200_17777_4_not_null
-- CHECK checkout_sessions.2200_17777_5_not_null
-- CHECK checkout_sessions.2200_17777_6_not_null
-- CHECK checkout_sessions.2200_17777_8_not_null
-- CHECK checkout_sessions.2200_17777_9_not_null
-- CHECK checkout_sessions.checkout_sessions_mode_check -> checkout_sessions.mode
-- PRIMARY KEY checkout_sessions.checkout_sessions_pkey (id) -> checkout_sessions.id
-- CHECK checkout_sessions.checkout_sessions_plan_check -> checkout_sessions.plan
-- UNIQUE checkout_sessions.checkout_sessions_stripe_session_id_key (stripe_session_id) -> checkout_sessions.stripe_session_id
-- CHECK data_quality_reviews.2200_18778_1_not_null
-- CHECK data_quality_reviews.2200_18778_3_not_null
-- CHECK data_quality_reviews.2200_18778_4_not_null
-- CHECK data_quality_reviews.2200_18778_5_not_null
-- CHECK data_quality_reviews.2200_18778_7_not_null
-- CHECK data_quality_reviews.2200_18778_8_not_null
-- FOREIGN KEY data_quality_reviews.data_quality_reviews_event_id_fkey (event_id) -> legal_events.id
-- CHECK data_quality_reviews.data_quality_reviews_issue_type_check -> data_quality_reviews.issue_type
-- CHECK data_quality_reviews.data_quality_reviews_note_check -> data_quality_reviews.note
-- PRIMARY KEY data_quality_reviews.data_quality_reviews_pkey (id) -> data_quality_reviews.id
-- CHECK data_quality_reviews.data_quality_reviews_status_check -> data_quality_reviews.status
-- CHECK entities.2200_18250_10_not_null
-- CHECK entities.2200_18250_11_not_null
-- CHECK entities.2200_18250_1_not_null
-- CHECK entities.2200_18250_2_not_null
-- CHECK entities.2200_18250_3_not_null
-- CHECK entities.2200_18250_9_not_null
-- CHECK entities.entities_entity_type_check -> entities.entity_type
-- PRIMARY KEY entities.entities_pkey (id) -> entities.id
-- CHECK entities.entities_status_check -> entities.status
-- CHECK entitlements.2200_18393_10_not_null
-- CHECK entitlements.2200_18393_1_not_null
-- CHECK entitlements.2200_18393_2_not_null
-- CHECK entitlements.2200_18393_3_not_null
-- CHECK entitlements.2200_18393_8_not_null
-- CHECK entitlements.2200_18393_9_not_null
-- PRIMARY KEY entitlements.entitlements_pkey (id) -> entitlements.id
-- CHECK entitlements.entitlements_plan_check -> entitlements.plan
-- UNIQUE entitlements.entitlements_plan_key (plan) -> entitlements.plan
-- CHECK entity_aliases.2200_18268_1_not_null
-- CHECK entity_aliases.2200_18268_2_not_null
-- CHECK entity_aliases.2200_18268_3_not_null
-- CHECK entity_aliases.2200_18268_4_not_null
-- CHECK entity_aliases.2200_18268_5_not_null
-- CHECK entity_aliases.2200_18268_6_not_null
-- CHECK entity_aliases.entity_aliases_alias_type_check -> entity_aliases.alias_type
-- CHECK entity_aliases.entity_aliases_confidence_check -> entity_aliases.confidence
-- UNIQUE entity_aliases.entity_aliases_entity_id_alias_alias_type_key (entity_id) -> entity_aliases.entity_id
-- UNIQUE entity_aliases.entity_aliases_entity_id_alias_alias_type_key (entity_id) -> entity_aliases.alias
-- UNIQUE entity_aliases.entity_aliases_entity_id_alias_alias_type_key (entity_id) -> entity_aliases.alias_type
-- UNIQUE entity_aliases.entity_aliases_entity_id_alias_alias_type_key (alias) -> entity_aliases.entity_id
-- UNIQUE entity_aliases.entity_aliases_entity_id_alias_alias_type_key (alias) -> entity_aliases.alias
-- UNIQUE entity_aliases.entity_aliases_entity_id_alias_alias_type_key (alias) -> entity_aliases.alias_type
-- UNIQUE entity_aliases.entity_aliases_entity_id_alias_alias_type_key (alias_type) -> entity_aliases.entity_id
-- UNIQUE entity_aliases.entity_aliases_entity_id_alias_alias_type_key (alias_type) -> entity_aliases.alias
-- UNIQUE entity_aliases.entity_aliases_entity_id_alias_alias_type_key (alias_type) -> entity_aliases.alias_type
-- FOREIGN KEY entity_aliases.entity_aliases_entity_id_fkey (entity_id) -> entities.id
-- PRIMARY KEY entity_aliases.entity_aliases_pkey (id) -> entity_aliases.id
-- CHECK entity_watchlist_members.2200_25811_1_not_null
-- CHECK entity_watchlist_members.2200_25811_2_not_null
-- CHECK entity_watchlist_members.2200_25811_3_not_null
-- FOREIGN KEY entity_watchlist_members.entity_watchlist_members_entity_id_fkey (entity_id) -> entities.id
-- PRIMARY KEY entity_watchlist_members.entity_watchlist_members_pkey (watchlist_id) -> entity_watchlist_members.watchlist_id
-- PRIMARY KEY entity_watchlist_members.entity_watchlist_members_pkey (watchlist_id) -> entity_watchlist_members.entity_id
-- PRIMARY KEY entity_watchlist_members.entity_watchlist_members_pkey (entity_id) -> entity_watchlist_members.watchlist_id
-- PRIMARY KEY entity_watchlist_members.entity_watchlist_members_pkey (entity_id) -> entity_watchlist_members.entity_id
-- FOREIGN KEY entity_watchlist_members.entity_watchlist_members_watchlist_id_fkey (watchlist_id) -> entity_watchlists.id
-- CHECK entity_watchlists.2200_24113_1_not_null
-- CHECK entity_watchlists.2200_24113_2_not_null
-- CHECK entity_watchlists.2200_24113_3_not_null
-- CHECK entity_watchlists.2200_24113_4_not_null
-- CHECK entity_watchlists.2200_24113_5_not_null
-- CHECK entity_watchlists.2200_24113_6_not_null
-- CHECK entity_watchlists.2200_24113_7_not_null
-- CHECK entity_watchlists.2200_24113_8_not_null
-- PRIMARY KEY entity_watchlists.entity_watchlists_pkey (id) -> entity_watchlists.id
-- CHECK event_evidence.2200_18351_1_not_null
-- CHECK event_evidence.2200_18351_2_not_null
-- CHECK event_evidence.2200_18351_3_not_null
-- CHECK event_evidence.2200_18351_5_not_null
-- CHECK event_evidence.2200_18351_6_not_null
-- CHECK event_evidence.2200_18351_7_not_null
-- FOREIGN KEY event_evidence.event_evidence_event_id_fkey (event_id) -> legal_events.id
-- CHECK event_evidence.event_evidence_evidence_type_check -> event_evidence.evidence_type
-- PRIMARY KEY event_evidence.event_evidence_pkey (id) -> event_evidence.id
-- CHECK event_news_coverage.2200_26543_1_not_null
-- CHECK event_news_coverage.2200_26543_2_not_null
-- CHECK event_news_coverage.2200_26543_3_not_null
-- CHECK event_news_coverage.2200_26543_4_not_null
-- CHECK event_news_coverage.2200_26543_6_not_null
-- CHECK event_news_coverage.2200_26543_7_not_null
-- FOREIGN KEY event_news_coverage.event_news_coverage_event_id_fkey (event_id) -> legal_events.id
-- CHECK event_news_coverage.event_news_coverage_order_check -> event_news_coverage.detected_at
-- CHECK event_news_coverage.event_news_coverage_order_check -> event_news_coverage.news_mentioned_at
-- PRIMARY KEY event_news_coverage.event_news_coverage_pkey (event_id) -> event_news_coverage.event_id
-- CHECK friction_score_history.2200_25770_10_not_null
-- CHECK friction_score_history.2200_25770_1_not_null
-- CHECK friction_score_history.2200_25770_2_not_null
-- CHECK friction_score_history.2200_25770_3_not_null
-- CHECK friction_score_history.2200_25770_4_not_null
-- CHECK friction_score_history.2200_25770_6_not_null
-- CHECK friction_score_history.2200_25770_7_not_null
-- CHECK friction_score_history.2200_25770_9_not_null
-- FOREIGN KEY friction_score_history.friction_score_history_entity_id_fkey (entity_id) -> entities.id
-- PRIMARY KEY friction_score_history.friction_score_history_pkey (id) -> friction_score_history.id
-- CHECK friction_scores.2200_18369_1_not_null
-- CHECK friction_scores.2200_18369_2_not_null
-- CHECK friction_scores.2200_18369_3_not_null
-- CHECK friction_scores.2200_18369_4_not_null
-- CHECK friction_scores.2200_18369_5_not_null
-- CHECK friction_scores.2200_18369_6_not_null
-- CHECK friction_scores.2200_18369_7_not_null
-- CHECK friction_scores.2200_18369_8_not_null
-- CHECK friction_scores.2200_18369_9_not_null
-- CHECK friction_scores.friction_scores_confidence_check -> friction_scores.confidence
-- FOREIGN KEY friction_scores.friction_scores_entity_id_fkey (entity_id) -> entities.id
-- PRIMARY KEY friction_scores.friction_scores_pkey (id) -> friction_scores.id
-- CHECK friction_scores.friction_scores_score_check -> friction_scores.score
-- CHECK friction_scores.friction_scores_trend_check -> friction_scores.trend
-- CHECK ghost_employers.2200_18080_1_not_null
-- CHECK ghost_employers.2200_18080_2_not_null
-- CHECK ghost_employers.2200_18080_3_not_null
-- CHECK ghost_employers.2200_18080_4_not_null
-- CHECK ghost_employers.ghost_employers_approx_headcount_check -> ghost_employers.approx_headcount
-- PRIMARY KEY ghost_employers.ghost_employers_pkey (slug) -> ghost_employers.slug
-- CHECK ghost_wall_posts.2200_18059_1_not_null
-- CHECK ghost_wall_posts.2200_18059_2_not_null
-- CHECK ghost_wall_posts.2200_18059_3_not_null
-- CHECK ghost_wall_posts.2200_18059_5_not_null
-- CHECK ghost_wall_posts.2200_18059_6_not_null
-- CHECK ghost_wall_posts.2200_18059_7_not_null
-- CHECK ghost_wall_posts.ghost_wall_posts_caption_check -> ghost_wall_posts.caption
-- FOREIGN KEY ghost_wall_posts.ghost_wall_posts_employer_slug_fkey (employer_slug) -> ghost_employers.slug
-- PRIMARY KEY ghost_wall_posts.ghost_wall_posts_pkey (id) -> ghost_wall_posts.id
-- CHECK ghost_wall_posts.ghost_wall_posts_status_check -> ghost_wall_posts.status
-- CHECK ghost_wall_posts.ghost_wall_posts_storage_path_format -> ghost_wall_posts.storage_path
-- FOREIGN KEY ghost_wall_posts.ghost_wall_posts_user_id_fkey (user_id)
-- CHECK ingest_runs.2200_18207_11_not_null
-- CHECK ingest_runs.2200_18207_1_not_null
-- CHECK ingest_runs.2200_18207_3_not_null
-- CHECK ingest_runs.2200_18207_4_not_null
-- CHECK ingest_runs.2200_18207_5_not_null
-- CHECK ingest_runs.2200_18207_7_not_null
-- CHECK ingest_runs.2200_18207_8_not_null
-- CHECK ingest_runs.ingest_runs_fetched_count_check -> ingest_runs.fetched_count
-- CHECK ingest_runs.ingest_runs_normalized_count_check -> ingest_runs.normalized_count
-- PRIMARY KEY ingest_runs.ingest_runs_pkey (id) -> ingest_runs.id
-- FOREIGN KEY ingest_runs.ingest_runs_source_id_fkey (source_id) -> source_catalog.id
-- CHECK ingest_runs.ingest_runs_status_check -> ingest_runs.status
-- CHECK legal_events.2200_18314_11_not_null
-- CHECK legal_events.2200_18314_12_not_null
-- CHECK legal_events.2200_18314_13_not_null
-- CHECK legal_events.2200_18314_14_not_null
-- CHECK legal_events.2200_18314_15_not_null
-- CHECK legal_events.2200_18314_16_not_null
-- CHECK legal_events.2200_18314_1_not_null
-- CHECK legal_events.2200_18314_2_not_null
-- CHECK legal_events.2200_18314_5_not_null
-- CHECK legal_events.2200_18314_6_not_null
-- CHECK legal_events.2200_18314_7_not_null
-- CHECK legal_events.2200_18314_8_not_null
-- CHECK legal_events.2200_18314_9_not_null
-- CHECK legal_events.legal_events_confidence_check -> legal_events.confidence
-- FOREIGN KEY legal_events.legal_events_entity_id_fkey (entity_id) -> entities.id
-- CHECK legal_events.legal_events_event_type_check -> legal_events.event_type
-- PRIMARY KEY legal_events.legal_events_pkey (id) -> legal_events.id
-- FOREIGN KEY legal_events.legal_events_raw_record_id_fkey (raw_record_id) -> raw_records.id
-- CHECK legal_events.legal_events_severity_check -> legal_events.severity
-- FOREIGN KEY legal_events.legal_events_source_id_fkey (source_id) -> source_catalog.id
-- CHECK legal_events.legal_events_status_check -> legal_events.status
-- CHECK map_cross_signals.2200_26753_10_not_null
-- CHECK map_cross_signals.2200_26753_11_not_null
-- CHECK map_cross_signals.2200_26753_12_not_null
-- CHECK map_cross_signals.2200_26753_13_not_null
-- CHECK map_cross_signals.2200_26753_14_not_null
-- CHECK map_cross_signals.2200_26753_15_not_null
-- CHECK map_cross_signals.2200_26753_16_not_null
-- CHECK map_cross_signals.2200_26753_17_not_null
-- CHECK map_cross_signals.2200_26753_18_not_null
-- CHECK map_cross_signals.2200_26753_1_not_null
-- CHECK map_cross_signals.2200_26753_2_not_null
-- CHECK map_cross_signals.2200_26753_3_not_null
-- CHECK map_cross_signals.2200_26753_4_not_null
-- CHECK map_cross_signals.2200_26753_5_not_null
-- CHECK map_cross_signals.2200_26753_6_not_null
-- CHECK map_cross_signals.2200_26753_8_not_null
-- CHECK map_cross_signals.2200_26753_9_not_null
-- CHECK map_cross_signals.map_cross_signals_correlation_key_type_check -> map_cross_signals.correlation_key_type
-- CHECK map_cross_signals.map_cross_signals_days_between_check -> map_cross_signals.days_between
-- FOREIGN KEY map_cross_signals.map_cross_signals_distress_entity_id_fkey (distress_entity_id) -> entities.id
-- FOREIGN KEY map_cross_signals.map_cross_signals_distress_event_id_fkey (distress_event_id) -> legal_events.id
-- CHECK map_cross_signals.map_cross_signals_distress_event_type_check -> map_cross_signals.distress_event_type
-- CHECK map_cross_signals.map_cross_signals_latitude_check -> map_cross_signals.latitude
-- CHECK map_cross_signals.map_cross_signals_location_confidence_check -> map_cross_signals.location_confidence
-- CHECK map_cross_signals.map_cross_signals_location_precision_check -> map_cross_signals.location_precision
-- CHECK map_cross_signals.map_cross_signals_longitude_check -> map_cross_signals.longitude
-- PRIMARY KEY map_cross_signals.map_cross_signals_pkey (id) -> map_cross_signals.id
-- FOREIGN KEY map_cross_signals.map_cross_signals_trade_entity_id_fkey (trade_entity_id) -> entities.id
-- UNIQUE map_cross_signals.map_cross_signals_trade_event_id_distress_event_id_key (trade_event_id) -> map_cross_signals.distress_event_id
-- UNIQUE map_cross_signals.map_cross_signals_trade_event_id_distress_event_id_key (trade_event_id) -> map_cross_signals.trade_event_id
-- UNIQUE map_cross_signals.map_cross_signals_trade_event_id_distress_event_id_key (distress_event_id) -> map_cross_signals.trade_event_id
-- UNIQUE map_cross_signals.map_cross_signals_trade_event_id_distress_event_id_key (distress_event_id) -> map_cross_signals.distress_event_id
-- FOREIGN KEY map_cross_signals.map_cross_signals_trade_event_id_fkey (trade_event_id) -> legal_events.id
-- CHECK map_cross_signals.map_cross_signals_trade_event_type_check -> map_cross_signals.trade_event_type
-- CHECK map_signal_locations.2200_26699_10_not_null
-- CHECK map_signal_locations.2200_26699_11_not_null
-- CHECK map_signal_locations.2200_26699_15_not_null
-- CHECK map_signal_locations.2200_26699_16_not_null
-- CHECK map_signal_locations.2200_26699_18_not_null
-- CHECK map_signal_locations.2200_26699_19_not_null
-- CHECK map_signal_locations.2200_26699_1_not_null
-- CHECK map_signal_locations.2200_26699_2_not_null
-- CHECK map_signal_locations.2200_26699_3_not_null
-- CHECK map_signal_locations.2200_26699_4_not_null
-- CHECK map_signal_locations.2200_26699_5_not_null
-- CHECK map_signal_locations.2200_26699_8_not_null
-- CHECK map_signal_locations.2200_26699_9_not_null
-- CHECK map_signal_locations.map_signal_location_resolution_check -> map_signal_locations.latitude
-- CHECK map_signal_locations.map_signal_location_resolution_check -> map_signal_locations.longitude
-- CHECK map_signal_locations.map_signal_location_resolution_check -> map_signal_locations.geocoding_confidence
-- FOREIGN KEY map_signal_locations.map_signal_locations_entity_id_fkey (entity_id) -> entities.id
-- FOREIGN KEY map_signal_locations.map_signal_locations_event_id_fkey (event_id) -> legal_events.id
-- CHECK map_signal_locations.map_signal_locations_geocoder_check -> map_signal_locations.geocoder
-- CHECK map_signal_locations.map_signal_locations_geocoding_confidence_check -> map_signal_locations.geocoding_confidence
-- CHECK map_signal_locations.map_signal_locations_latitude_check -> map_signal_locations.latitude
-- CHECK map_signal_locations.map_signal_locations_location_precision_check -> map_signal_locations.location_precision
-- CHECK map_signal_locations.map_signal_locations_longitude_check -> map_signal_locations.longitude
-- PRIMARY KEY map_signal_locations.map_signal_locations_pkey (event_id) -> map_signal_locations.event_id
-- CHECK map_signal_locations.map_signal_locations_signal_group_check -> map_signal_locations.signal_group
-- CHECK market_events.2200_17796_1_not_null
-- CHECK market_events.2200_17796_3_not_null
-- CHECK market_events.2200_17796_6_not_null
-- CHECK market_events.2200_17796_7_not_null
-- CHECK market_events.2200_17796_8_not_null
-- CHECK market_events.market_events_event_type_check -> market_events.event_type
-- FOREIGN KEY market_events.market_events_market_id_fkey (market_id) -> markets.id
-- PRIMARY KEY market_events.market_events_pkey (id) -> market_events.id
-- CHECK market_events.market_events_probability_check -> market_events.probability
-- CHECK markets.2200_17546_1_not_null
-- CHECK markets.2200_17546_3_not_null
-- CHECK markets.2200_17546_7_not_null
-- CHECK markets.2200_17546_8_not_null
-- CHECK markets.markets_outcome_check -> markets.outcome
-- PRIMARY KEY markets.markets_pkey (id) -> markets.id
-- UNIQUE markets.markets_slug_key (slug) -> markets.slug
-- CHECK markets.markets_yes_price_check -> markets.yes_price
-- CHECK paper_predictions.2200_17905_1_not_null
-- CHECK paper_predictions.2200_17905_2_not_null
-- CHECK paper_predictions.2200_17905_3_not_null
-- CHECK paper_predictions.2200_17905_4_not_null
-- CHECK paper_predictions.2200_17905_6_not_null
-- CHECK paper_predictions.2200_17905_7_not_null
-- CHECK paper_predictions.2200_17905_8_not_null
-- FOREIGN KEY paper_predictions.paper_predictions_market_id_fkey (market_id) -> markets.id
-- PRIMARY KEY paper_predictions.paper_predictions_pkey (id) -> paper_predictions.id
-- CHECK paper_predictions.paper_predictions_probability_check -> paper_predictions.probability
-- CHECK paper_predictions.paper_predictions_side_check -> paper_predictions.side
-- FOREIGN KEY paper_predictions.paper_predictions_user_id_fkey (user_id)
-- UNIQUE paper_predictions.paper_predictions_user_id_market_id_key (user_id) -> paper_predictions.user_id
-- UNIQUE paper_predictions.paper_predictions_user_id_market_id_key (user_id) -> paper_predictions.market_id
-- UNIQUE paper_predictions.paper_predictions_user_id_market_id_key (market_id) -> paper_predictions.user_id
-- UNIQUE paper_predictions.paper_predictions_user_id_market_id_key (market_id) -> paper_predictions.market_id
-- CHECK profiles.2200_17834_1_not_null
-- CHECK profiles.2200_17834_4_not_null
-- CHECK profiles.2200_17834_5_not_null
-- CHECK profiles.2200_17834_6_not_null
-- FOREIGN KEY profiles.profiles_id_fkey (id)
-- PRIMARY KEY profiles.profiles_pkey (id) -> profiles.id
-- CHECK profiles.profiles_tier_check -> profiles.tier
-- CHECK query_audit_events.2200_18764_1_not_null
-- CHECK query_audit_events.2200_18764_3_not_null
-- CHECK query_audit_events.2200_18764_4_not_null
-- CHECK query_audit_events.2200_18764_5_not_null
-- CHECK query_audit_events.2200_18764_6_not_null
-- PRIMARY KEY query_audit_events.query_audit_events_pkey (id) -> query_audit_events.id
-- CHECK query_audit_events.query_audit_events_result_count_check -> query_audit_events.result_count
-- CHECK query_audit_events.query_audit_events_surface_check -> query_audit_events.surface
-- CHECK raw_records.2200_18289_10_not_null
-- CHECK raw_records.2200_18289_1_not_null
-- CHECK raw_records.2200_18289_5_not_null
-- CHECK raw_records.2200_18289_8_not_null
-- CHECK raw_records.2200_18289_9_not_null
-- FOREIGN KEY raw_records.raw_records_ingest_run_id_fkey (ingest_run_id) -> ingest_runs.id
-- CHECK raw_records.raw_records_normalized_status_check -> raw_records.normalized_status
-- UNIQUE raw_records.raw_records_payload_hash_key (payload_hash) -> raw_records.payload_hash
-- PRIMARY KEY raw_records.raw_records_pkey (id) -> raw_records.id
-- FOREIGN KEY raw_records.raw_records_source_id_fkey (source_id) -> source_catalog.id
-- CHECK read_audit_events.2200_18484_1_not_null
-- CHECK read_audit_events.2200_18484_3_not_null
-- CHECK read_audit_events.2200_18484_5_not_null
-- CHECK read_audit_events.2200_18484_6_not_null
-- PRIMARY KEY read_audit_events.read_audit_events_pkey (id) -> read_audit_events.id
-- CHECK read_audit_events.read_audit_events_surface_check -> read_audit_events.surface
-- CHECK sales_leads.2200_18715_10_not_null
-- CHECK sales_leads.2200_18715_11_not_null
-- CHECK sales_leads.2200_18715_1_not_null
-- CHECK sales_leads.2200_18715_2_not_null
-- CHECK sales_leads.2200_18715_3_not_null
-- CHECK sales_leads.2200_18715_4_not_null
-- CHECK sales_leads.2200_18715_5_not_null
-- CHECK sales_leads.2200_18715_6_not_null
-- CHECK sales_leads.2200_18715_7_not_null
-- CHECK sales_leads.2200_18715_8_not_null
-- CHECK sales_leads.2200_18715_9_not_null
-- CHECK sales_leads.sales_leads_company_check -> sales_leads.company
-- CHECK sales_leads.sales_leads_message_check -> sales_leads.message
-- CHECK sales_leads.sales_leads_name_check -> sales_leads.name
-- PRIMARY KEY sales_leads.sales_leads_pkey (id) -> sales_leads.id
-- CHECK sales_leads.sales_leads_status_check -> sales_leads.status
-- CHECK sales_leads.sales_leads_use_case_check -> sales_leads.use_case
-- CHECK search_term_signals.2200_18228_10_not_null
-- CHECK search_term_signals.2200_18228_11_not_null
-- CHECK search_term_signals.2200_18228_1_not_null
-- CHECK search_term_signals.2200_18228_3_not_null
-- CHECK search_term_signals.2200_18228_4_not_null
-- CHECK search_term_signals.2200_18228_5_not_null
-- CHECK search_term_signals.2200_18228_6_not_null
-- CHECK search_term_signals.2200_18228_7_not_null
-- CHECK search_term_signals.2200_18228_8_not_null
-- CHECK search_term_signals.2200_18228_9_not_null
-- CHECK search_term_signals.search_term_signals_baseline_count_check -> search_term_signals.baseline_count
-- CHECK search_term_signals.search_term_signals_current_count_check -> search_term_signals.current_count
-- PRIMARY KEY search_term_signals.search_term_signals_pkey (id) -> search_term_signals.id
-- FOREIGN KEY search_term_signals.search_term_signals_source_id_fkey (source_id) -> source_catalog.id
-- CHECK search_term_signals.search_term_signals_surge_ratio_check -> search_term_signals.surge_ratio
-- CHECK service_requests.2200_18647_10_not_null
-- CHECK service_requests.2200_18647_11_not_null
-- CHECK service_requests.2200_18647_1_not_null
-- CHECK service_requests.2200_18647_2_not_null
-- CHECK service_requests.2200_18647_3_not_null
-- CHECK service_requests.2200_18647_4_not_null
-- CHECK service_requests.2200_18647_5_not_null
-- CHECK service_requests.2200_18647_7_not_null
-- CHECK service_requests.2200_18647_8_not_null
-- CHECK service_requests.2200_18647_9_not_null
-- CHECK service_requests.service_requests_details_check -> service_requests.details
-- PRIMARY KEY service_requests.service_requests_pkey (id) -> service_requests.id
-- FOREIGN KEY service_requests.service_requests_plan_fkey (plan) -> entitlements.plan
-- CHECK service_requests.service_requests_priority_check -> service_requests.priority
-- CHECK service_requests.service_requests_request_type_check -> service_requests.request_type
-- CHECK service_requests.service_requests_status_check -> service_requests.status
-- CHECK service_requests.service_requests_subject_check -> service_requests.subject
-- CHECK source_catalog.2200_18184_10_not_null
-- CHECK source_catalog.2200_18184_13_not_null
-- CHECK source_catalog.2200_18184_14_not_null
-- CHECK source_catalog.2200_18184_15_not_null
-- CHECK source_catalog.2200_18184_16_not_null
-- CHECK source_catalog.2200_18184_1_not_null
-- CHECK source_catalog.2200_18184_20_not_null
-- CHECK source_catalog.2200_18184_2_not_null
-- CHECK source_catalog.2200_18184_3_not_null
-- CHECK source_catalog.2200_18184_4_not_null
-- CHECK source_catalog.2200_18184_5_not_null
-- CHECK source_catalog.2200_18184_6_not_null
-- CHECK source_catalog.2200_18184_7_not_null
-- CHECK source_catalog.2200_18184_8_not_null
-- CHECK source_catalog.source_catalog_access_method_check -> source_catalog.access_method
-- PRIMARY KEY source_catalog.source_catalog_pkey (id) -> source_catalog.id
-- CHECK source_catalog.source_catalog_rate_limit_per_hour_check -> source_catalog.rate_limit_per_hour
-- UNIQUE source_catalog.source_catalog_slug_key (slug) -> source_catalog.slug
-- CHECK source_catalog.source_catalog_terms_status_check -> source_catalog.terms_status
-- CHECK waitlist_signups.2200_17754_1_not_null
-- CHECK waitlist_signups.2200_17754_2_not_null
-- CHECK waitlist_signups.2200_17754_3_not_null
-- CHECK waitlist_signups.2200_17754_4_not_null
-- CHECK waitlist_signups.2200_17754_5_not_null
-- CHECK waitlist_signups.2200_17754_6_not_null
-- CHECK waitlist_signups.2200_17754_7_not_null
-- CHECK waitlist_signups.waitlist_email_format -> waitlist_signups.email
-- UNIQUE waitlist_signups.waitlist_signups_email_key (email) -> waitlist_signups.email
-- PRIMARY KEY waitlist_signups.waitlist_signups_pkey (id) -> waitlist_signups.id
-- CHECK waitlist_signups.waitlist_signups_status_check -> waitlist_signups.status
-- CHECK watchlist_alert_deliveries.2200_26337_1_not_null
-- CHECK watchlist_alert_deliveries.2200_26337_2_not_null
-- CHECK watchlist_alert_deliveries.2200_26337_3_not_null
-- CHECK watchlist_alert_deliveries.2200_26337_4_not_null
-- CHECK watchlist_alert_deliveries.2200_26337_7_not_null
-- FOREIGN KEY watchlist_alert_deliveries.watchlist_alert_deliveries_entity_id_fkey (entity_id) -> entities.id
-- FOREIGN KEY watchlist_alert_deliveries.watchlist_alert_deliveries_event_id_fkey (event_id) -> legal_events.id
-- PRIMARY KEY watchlist_alert_deliveries.watchlist_alert_deliveries_pkey (id) -> watchlist_alert_deliveries.id
-- UNIQUE watchlist_alert_deliveries.watchlist_alert_deliveries_user_id_event_id_key (user_id) -> watchlist_alert_deliveries.user_id
-- UNIQUE watchlist_alert_deliveries.watchlist_alert_deliveries_user_id_event_id_key (user_id) -> watchlist_alert_deliveries.event_id
-- UNIQUE watchlist_alert_deliveries.watchlist_alert_deliveries_user_id_event_id_key (event_id) -> watchlist_alert_deliveries.user_id
-- UNIQUE watchlist_alert_deliveries.watchlist_alert_deliveries_user_id_event_id_key (event_id) -> watchlist_alert_deliveries.event_id
-- CHECK watchlist_entities.2200_18434_1_not_null
-- CHECK watchlist_entities.2200_18434_2_not_null
-- CHECK watchlist_entities.2200_18434_5_not_null
-- FOREIGN KEY watchlist_entities.watchlist_entities_entity_id_fkey (entity_id) -> entities.id
-- PRIMARY KEY watchlist_entities.watchlist_entities_pkey (id) -> watchlist_entities.id
-- FOREIGN KEY watchlist_entities.watchlist_entities_watchlist_id_fkey (watchlist_id) -> watchlists.id
-- CHECK watchlist_entities.watchlist_entity_or_query -> watchlist_entities.query
-- CHECK watchlist_entities.watchlist_entity_or_query -> watchlist_entities.entity_id
-- CHECK watchlists.2200_17882_1_not_null
-- CHECK watchlists.2200_17882_2_not_null
-- CHECK watchlists.2200_17882_3_not_null
-- CHECK watchlists.2200_17882_4_not_null
-- FOREIGN KEY watchlists.watchlists_market_id_fkey (market_id) -> markets.id
-- PRIMARY KEY watchlists.watchlists_pkey (id) -> watchlists.id
-- FOREIGN KEY watchlists.watchlists_user_id_fkey (user_id)
-- UNIQUE watchlists.watchlists_user_id_market_id_key (user_id) -> watchlists.market_id
-- UNIQUE watchlists.watchlists_user_id_market_id_key (user_id) -> watchlists.user_id
-- UNIQUE watchlists.watchlists_user_id_market_id_key (market_id) -> watchlists.market_id
-- UNIQUE watchlists.watchlists_user_id_market_id_key (market_id) -> watchlists.user_id

-- Indexes
CREATE UNIQUE INDEX alert_configs_pkey ON public.alert_configs USING btree (id);
CREATE UNIQUE INDEX alerts_pkey ON public.alerts USING btree (id);
CREATE UNIQUE INDEX api_subscribers_owner_email_key ON public.api_subscribers USING btree (owner_email);
CREATE UNIQUE INDEX api_subscribers_pkey ON public.api_subscribers USING btree (id);
CREATE UNIQUE INDEX api_subscribers_token_hash_key ON public.api_subscribers USING btree (token_hash);
CREATE UNIQUE INDEX app_profiles_email_key ON public.app_profiles USING btree (email);
CREATE UNIQUE INDEX app_profiles_pkey ON public.app_profiles USING btree (user_id);
CREATE INDEX case_stories_event_idx ON public.case_stories USING btree (event_id);
CREATE UNIQUE INDEX case_stories_pkey ON public.case_stories USING btree (id);
CREATE UNIQUE INDEX case_stories_slug_key ON public.case_stories USING btree (slug);
CREATE INDEX case_stories_status_idx ON public.case_stories USING btree (status, created_at DESC);
CREATE INDEX checkout_sessions_created_at_idx ON public.checkout_sessions USING btree (created_at DESC);
CREATE UNIQUE INDEX checkout_sessions_pkey ON public.checkout_sessions USING btree (id);
CREATE INDEX checkout_sessions_plan_idx ON public.checkout_sessions USING btree (plan);
CREATE UNIQUE INDEX checkout_sessions_stripe_session_id_key ON public.checkout_sessions USING btree (stripe_session_id);
CREATE UNIQUE INDEX data_quality_reviews_pkey ON public.data_quality_reviews USING btree (id);
CREATE INDEX entities_canonical_name_trgm_idx ON public.entities USING gin (canonical_name gin_trgm_ops);
CREATE INDEX entities_cik_idx ON public.entities USING btree (cik) WHERE (cik IS NOT NULL);
CREATE UNIQUE INDEX entities_cik_uidx ON public.entities USING btree (cik) WHERE ((cik IS NOT NULL) AND (cik <> ''::text));
CREATE INDEX entities_name_idx ON public.entities USING btree (canonical_name);
CREATE INDEX entities_normalized_name_idx ON public.entities USING btree (normalized_name);
CREATE INDEX entities_normalized_name_trgm_idx ON public.entities USING gin (normalized_name gin_trgm_ops);
CREATE UNIQUE INDEX entities_pkey ON public.entities USING btree (id);
CREATE INDEX entities_ticker_idx ON public.entities USING btree (ticker);
CREATE INDEX idx_companies_ticker ON public.entities USING btree (ticker) WHERE (ticker IS NOT NULL);
CREATE UNIQUE INDEX entitlements_pkey ON public.entitlements USING btree (id);
CREATE UNIQUE INDEX entitlements_plan_key ON public.entitlements USING btree (plan);
CREATE UNIQUE INDEX entity_aliases_entity_id_alias_alias_type_key ON public.entity_aliases USING btree (entity_id, alias, alias_type);
CREATE INDEX entity_aliases_entity_id_idx ON public.entity_aliases USING btree (entity_id);
CREATE UNIQUE INDEX entity_aliases_normalized_uidx ON public.entity_aliases USING btree (normalized_alias) WHERE ((normalized_alias IS NOT NULL) AND (normalized_alias <> ''::text));
CREATE UNIQUE INDEX entity_aliases_pkey ON public.entity_aliases USING btree (id);
CREATE INDEX entity_watchlist_members_entity_idx ON public.entity_watchlist_members USING btree (entity_id);
CREATE UNIQUE INDEX entity_watchlist_members_pkey ON public.entity_watchlist_members USING btree (watchlist_id, entity_id);
CREATE INDEX entity_watchlist_members_watchlist_idx ON public.entity_watchlist_members USING btree (watchlist_id);
CREATE UNIQUE INDEX entity_watchlists_pkey ON public.entity_watchlists USING btree (id);
CREATE INDEX entity_watchlists_user_id_idx ON public.entity_watchlists USING btree (user_id);
CREATE UNIQUE INDEX event_evidence_pkey ON public.event_evidence USING btree (id);
CREATE INDEX event_news_coverage_news_mentioned_idx ON public.event_news_coverage USING btree (news_mentioned_at DESC);
CREATE UNIQUE INDEX event_news_coverage_pkey ON public.event_news_coverage USING btree (event_id);
CREATE INDEX friction_score_history_entity_time_idx ON public.friction_score_history USING btree (entity_id, computed_at DESC);
CREATE UNIQUE INDEX friction_score_history_pkey ON public.friction_score_history USING btree (id);
CREATE INDEX friction_scores_entity_time_idx ON public.friction_scores USING btree (entity_id, computed_at DESC);
CREATE UNIQUE INDEX friction_scores_entity_uidx ON public.friction_scores USING btree (entity_id);
CREATE UNIQUE INDEX friction_scores_pkey ON public.friction_scores USING btree (id);
CREATE INDEX friction_scores_score_idx ON public.friction_scores USING btree (score DESC);
CREATE UNIQUE INDEX ghost_employers_pkey ON public.ghost_employers USING btree (slug);
CREATE UNIQUE INDEX ghost_wall_posts_pkey ON public.ghost_wall_posts USING btree (id);
CREATE INDEX ghost_wall_posts_status_created_idx ON public.ghost_wall_posts USING btree (status, created_at DESC);
CREATE UNIQUE INDEX ingest_runs_pkey ON public.ingest_runs USING btree (id);
CREATE INDEX legal_events_entity_date_idx ON public.legal_events USING btree (entity_id, filing_date DESC);
CREATE INDEX legal_events_filing_date_idx ON public.legal_events USING btree (filing_date DESC NULLS LAST);
CREATE UNIQUE INDEX legal_events_pkey ON public.legal_events USING btree (id);
CREATE INDEX legal_events_raw_record_id_idx ON public.legal_events USING btree (raw_record_id);
CREATE INDEX legal_events_trade_date_idx ON public.legal_events USING btree (trade_date DESC NULLS LAST);
CREATE INDEX legal_events_type_filing_date_idx ON public.legal_events USING btree (event_type, filing_date DESC NULLS LAST);
CREATE INDEX legal_events_type_idx ON public.legal_events USING btree (event_type);
CREATE INDEX map_cross_signals_bounds_idx ON public.map_cross_signals USING btree (longitude, latitude);
CREATE INDEX map_cross_signals_dates_idx ON public.map_cross_signals USING btree (distress_date DESC, trade_date DESC);
CREATE UNIQUE INDEX map_cross_signals_pkey ON public.map_cross_signals USING btree (id);
CREATE UNIQUE INDEX map_cross_signals_trade_event_id_distress_event_id_key ON public.map_cross_signals USING btree (trade_event_id, distress_event_id);
CREATE INDEX map_cross_signals_type_bounds_idx ON public.map_cross_signals USING btree (trade_event_type, distress_event_type, longitude, latitude);
CREATE INDEX map_signal_locations_bounds_idx ON public.map_signal_locations USING btree (longitude, latitude) WHERE (geocoding_confidence <> 'unresolved'::text);
CREATE UNIQUE INDEX map_signal_locations_pkey ON public.map_signal_locations USING btree (event_id);
CREATE INDEX map_signal_locations_type_bounds_idx ON public.map_signal_locations USING btree (event_type, longitude, latitude) WHERE ((geocoding_confidence <> 'unresolved'::text) AND (longitude IS NOT NULL) AND (latitude IS NOT NULL));
CREATE INDEX map_signal_locations_type_date_idx ON public.map_signal_locations USING btree (event_type, filing_date DESC);
CREATE INDEX map_signal_locations_unresolved_idx ON public.map_signal_locations USING btree (attempted_at DESC) WHERE (geocoding_confidence = 'unresolved'::text);
CREATE INDEX market_events_market_created_idx ON public.market_events USING btree (market_id, created_at DESC);
CREATE UNIQUE INDEX market_events_pkey ON public.market_events USING btree (id);
CREATE INDEX markets_outcome_idx ON public.markets USING btree (outcome);
CREATE UNIQUE INDEX markets_pkey ON public.markets USING btree (id);
CREATE UNIQUE INDEX markets_slug_key ON public.markets USING btree (slug);
CREATE INDEX markets_updated_at_idx ON public.markets USING btree (updated_at DESC);
CREATE UNIQUE INDEX paper_predictions_pkey ON public.paper_predictions USING btree (id);
CREATE INDEX paper_predictions_user_created_idx ON public.paper_predictions USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX paper_predictions_user_id_market_id_key ON public.paper_predictions USING btree (user_id, market_id);
CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);
CREATE UNIQUE INDEX query_audit_events_pkey ON public.query_audit_events USING btree (id);
CREATE UNIQUE INDEX raw_records_payload_hash_key ON public.raw_records USING btree (payload_hash);
CREATE UNIQUE INDEX raw_records_pkey ON public.raw_records USING btree (id);
CREATE INDEX raw_records_source_record_idx ON public.raw_records USING btree (source_id, source_record_id);
CREATE UNIQUE INDEX raw_records_source_record_uidx ON public.raw_records USING btree (source_id, source_record_id);
CREATE UNIQUE INDEX read_audit_events_pkey ON public.read_audit_events USING btree (id);
CREATE INDEX sales_leads_email_idx ON public.sales_leads USING btree (email);
CREATE UNIQUE INDEX sales_leads_pkey ON public.sales_leads USING btree (id);
CREATE INDEX sales_leads_status_time_idx ON public.sales_leads USING btree (status, created_at DESC);
CREATE UNIQUE INDEX search_term_signals_pkey ON public.search_term_signals USING btree (id);
CREATE UNIQUE INDEX service_requests_pkey ON public.service_requests USING btree (id);
CREATE UNIQUE INDEX source_catalog_pkey ON public.source_catalog USING btree (id);
CREATE UNIQUE INDEX source_catalog_slug_key ON public.source_catalog USING btree (slug);
CREATE UNIQUE INDEX waitlist_signups_email_key ON public.waitlist_signups USING btree (email);
CREATE UNIQUE INDEX waitlist_signups_email_lower_key ON public.waitlist_signups USING btree (lower((email)::text));
CREATE UNIQUE INDEX waitlist_signups_pkey ON public.waitlist_signups USING btree (id);
CREATE INDEX watchlist_alert_deliveries_event_idx ON public.watchlist_alert_deliveries USING btree (event_id);
CREATE UNIQUE INDEX watchlist_alert_deliveries_pkey ON public.watchlist_alert_deliveries USING btree (id);
CREATE INDEX watchlist_alert_deliveries_user_created_idx ON public.watchlist_alert_deliveries USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX watchlist_alert_deliveries_user_id_event_id_key ON public.watchlist_alert_deliveries USING btree (user_id, event_id);
CREATE UNIQUE INDEX watchlist_entities_pkey ON public.watchlist_entities USING btree (id);
CREATE UNIQUE INDEX watchlists_pkey ON public.watchlists USING btree (id);
CREATE INDEX watchlists_user_created_idx ON public.watchlists USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX watchlists_user_id_market_id_key ON public.watchlists USING btree (user_id, market_id);

-- Functions
-- FUNCTION create_profile_for_new_user
CREATE OR REPLACE FUNCTION public.create_profile_for_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$function$
;

-- FUNCTION ingest_legal_records
CREATE OR REPLACE FUNCTION public.ingest_legal_records(source jsonb, records jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
declare
  source_uuid uuid;
  raw_uuid uuid;
  entity_uuid uuid;
  event_uuid uuid;
  item jsonb;
  raw_payload jsonb;
  event_payload jsonb;
  inserted_count integer := 0;
  skipped_count integer := 0;
  updated_count integer := 0;
  error_count integer := 0;
  entity_name text;
  normalized text;
  score_value integer;
  confidence_value integer;
  source_record_key text;
  incoming_hash text;
  item_error text;
  owner_cik text;
  issuer_cik text;
  entity_cik text;
begin
  insert into public.source_catalog (
    slug, name, jurisdiction, record_type, access_method, terms_status, refresh_cadence,
    source_url, enabled, notes, last_success_at, adapter_kind, rate_limit_per_hour,
    auth_env_var, terms_reviewed_at, disabled_reason, config
  )
  values (
    source->>'slug', source->>'name', source->>'jurisdiction', source->>'record_type',
    source->>'access_method', source->>'terms_status', coalesce(source->>'refresh_cadence', 'daily'),
    source->>'source_url', coalesce((source->>'enabled')::boolean, true), source->>'notes',
    nullif(source->>'last_success_at', '')::timestamptz,
    coalesce(source->>'adapter_kind', 'manual'),
    coalesce((source->>'rate_limit_per_hour')::integer, 60),
    nullif(source->>'auth_env_var', ''),
    coalesce((source->>'terms_reviewed_at')::timestamptz, now()),
    nullif(source->>'disabled_reason', ''),
    coalesce(source->'config', '{}'::jsonb)
  )
  on conflict (slug) do update
  set
    name = excluded.name,
    jurisdiction = excluded.jurisdiction,
    record_type = excluded.record_type,
    access_method = excluded.access_method,
    terms_status = excluded.terms_status,
    refresh_cadence = excluded.refresh_cadence,
    source_url = excluded.source_url,
    enabled = excluded.enabled,
    notes = excluded.notes,
    last_success_at = coalesce(excluded.last_success_at, source_catalog.last_success_at),
    adapter_kind = excluded.adapter_kind,
    rate_limit_per_hour = excluded.rate_limit_per_hour,
    auth_env_var = excluded.auth_env_var,
    terms_reviewed_at = excluded.terms_reviewed_at,
    disabled_reason = excluded.disabled_reason,
    config = excluded.config,
    updated_at = now()
  returning id into source_uuid;

  for item in select * from jsonb_array_elements(coalesce(records, '[]'::jsonb))
  loop
    begin
      raw_payload := item->'raw';
      event_payload := item->'event';
      source_record_key := nullif(trim(raw_payload->>'source_record_id'), '');
      incoming_hash := nullif(trim(raw_payload->>'payload_hash'), '');

      if source_record_key is null or incoming_hash is null then
        skipped_count := skipped_count + 1;
        continue;
      end if;

      insert into public.raw_records (
        source_id, source_record_id, payload_hash, fetched_url, source_timestamp,
        retrieved_at, normalized_status, payload
      )
      values (
        source_uuid, source_record_key, incoming_hash, raw_payload->>'fetched_url',
        coalesce((raw_payload->>'source_timestamp')::timestamptz, now()),
        coalesce((raw_payload->>'retrieved_at')::timestamptz, now()),
        'normalized', coalesce(raw_payload->'payload', '{}'::jsonb)
      )
      on conflict (source_id, source_record_id) do update
      set
        payload_hash = case
          when excluded.payload_hash is not distinct from raw_records.payload_hash then raw_records.payload_hash
          when not exists (
            select 1 from public.raw_records x
            where x.payload_hash = excluded.payload_hash and x.id <> raw_records.id
          ) then excluded.payload_hash
          else raw_records.payload_hash
        end,
        fetched_url = excluded.fetched_url,
        source_timestamp = excluded.source_timestamp,
        retrieved_at = excluded.retrieved_at,
        normalized_status = 'normalized',
        payload = excluded.payload
      returning id into raw_uuid;

      select id into event_uuid from public.legal_events where raw_record_id = raw_uuid limit 1;

      entity_name := nullif(trim(event_payload->>'entity_name'), '');
      normalized := public.normalize_entity_name(entity_name);
      owner_cik := nullif(regexp_replace(coalesce(event_payload->>'owner_cik', ''), '[^0-9]', '', 'g'), '');
      issuer_cik := nullif(regexp_replace(coalesce(event_payload->>'issuer_cik', ''), '[^0-9]', '', 'g'), '');
      entity_cik := coalesce(owner_cik, issuer_cik);

      if entity_name is null then
        skipped_count := skipped_count + 1;
        event_uuid := null;
        entity_uuid := null;
        continue;
      end if;

      entity_uuid := null;

      if entity_cik is not null then
        select id into entity_uuid from public.entities where cik = entity_cik limit 1;
      end if;

      if entity_uuid is null then
        select ea.entity_id into entity_uuid
        from public.entity_aliases ea
        where ea.normalized_alias = normalized
        limit 1;
      end if;

      if entity_uuid is null then
        select id into entity_uuid
        from public.entities
        where normalized_name = normalized
        order by updated_at desc nulls last
        limit 1;
      end if;

      if entity_uuid is null then
        select id into entity_uuid
        from public.entities
        where canonical_name = entity_name
        limit 1;
      end if;

      if entity_uuid is null then
        insert into public.entities (
          canonical_name, normalized_name, entity_type, jurisdiction, status, cik
        )
        values (
          entity_name, normalized, 'company',
          event_payload->>'jurisdiction', 'unknown', entity_cik
        )
        returning id into entity_uuid;
      else
        update public.entities
        set
          normalized_name = coalesce(nullif(normalized_name, ''), normalized),
          cik = coalesce(nullif(cik, ''), entity_cik),
          updated_at = now()
        where id = entity_uuid
          and (
            normalized_name is null or normalized_name = ''
            or (entity_cik is not null and (cik is null or cik = ''))
          );
      end if;

      if normalized is not null and not exists (
        select 1 from public.entity_aliases ea where ea.normalized_alias = normalized
      ) then
        begin
          insert into public.entity_aliases (entity_id, alias, alias_type, confidence, normalized_alias, source)
          values (entity_uuid, entity_name, 'name', 90, normalized, coalesce(source->>'slug', 'ingest'));
        exception when others then
          null;
        end;
      end if;

      score_value := least(100, greatest(0, public.json_text_as_int(event_payload->>'severity', 50)));
      confidence_value := least(100, greatest(0, public.json_text_as_int(event_payload->>'confidence', 80)));

      if event_uuid is not null then
        update public.legal_events
        set
          entity_id = entity_uuid,
          event_type = coalesce(nullif(event_payload->>'event_type', ''), event_type),
          title = coalesce(nullif(event_payload->>'title', ''), title),
          summary = coalesce(nullif(event_payload->>'summary', ''), summary),
          jurisdiction = coalesce(nullif(event_payload->>'jurisdiction', ''), jurisdiction),
          filing_date = coalesce(nullif(event_payload->>'filing_date', '')::date, filing_date),
          trade_date = coalesce(nullif(event_payload->>'trade_date', '')::date, trade_date),
          amount = coalesce(nullif(event_payload->>'amount', '')::numeric, amount),
          severity = coalesce(public.json_text_as_int(event_payload->>'severity', null), severity),
          confidence = coalesce(nullif(event_payload->>'confidence', '')::numeric, confidence),
          status = coalesce(nullif(event_payload->>'status', ''), status),
          updated_at = now()
        where id = event_uuid;
        updated_count := updated_count + 1;
      else
        insert into public.legal_events (
          entity_id, source_id, raw_record_id, event_type, title, summary, jurisdiction,
          filing_date, trade_date, amount, severity, confidence, status, allegation_disclaimer
        )
        values (
          entity_uuid, source_uuid, raw_uuid, event_payload->>'event_type',
          event_payload->>'title', event_payload->>'summary', event_payload->>'jurisdiction',
          nullif(event_payload->>'filing_date', '')::date,
          nullif(event_payload->>'trade_date', '')::date,
          nullif(event_payload->>'amount', '')::numeric,
          score_value, confidence_value,
          coalesce(nullif(event_payload->>'status', ''), 'open'),
          'This record is an allegation or administrative filing, not a judgment.'
        )
        returning id into event_uuid;

        if nullif(event_payload->>'evidence_url', '') is not null then
          insert into public.event_evidence (
            event_id, source_url, document_id, evidence_type, metadata
          )
          values (
            event_uuid, event_payload->>'evidence_url', source_record_key, 'source_link',
            jsonb_build_object(
              'source_slug', source->>'slug',
              'trade_date', event_payload->>'trade_date',
              'grain', event_payload->>'grain'
            )
          );
        end if;
        inserted_count := inserted_count + 1;
      end if;

      if not exists (
        select 1 from public.friction_scores fs
        where fs.entity_id = entity_uuid
          and fs.score = score_value
          and fs.confidence = confidence_value
      ) then
        insert into public.friction_score_history (
          entity_id, score, confidence, trend, reasons, category_scores, model_version, computed_at
        )
        values (
          entity_uuid, score_value, confidence_value, 'flat',
          jsonb_build_array(jsonb_build_object('label', event_payload->>'title', 'weight', least(50, greatest(0, score_value / 2)))),
          jsonb_build_object(coalesce(event_payload->>'event_type', 'public_record'), score_value),
          'scheduled-ingest-v2', now()
        );
      end if;

      insert into public.friction_scores (
        entity_id, score, confidence, trend, reasons, category_scores, model_version, computed_at
      )
      values (
        entity_uuid, score_value, confidence_value, 'flat',
        jsonb_build_array(jsonb_build_object('label', event_payload->>'title', 'weight', least(50, greatest(0, score_value / 2)))),
        jsonb_build_object(coalesce(event_payload->>'event_type', 'public_record'), score_value),
        'scheduled-ingest-v2', now()
      )
      on conflict (entity_id) do update
      set
        score = excluded.score,
        confidence = excluded.confidence,
        trend = excluded.trend,
        reasons = excluded.reasons,
        category_scores = excluded.category_scores,
        model_version = excluded.model_version,
        computed_at = excluded.computed_at;

      event_uuid := null;
      entity_uuid := null;
      raw_uuid := null;
    exception when others then
      error_count := error_count + 1;
      item_error := SQLERRM;
      raise warning 'ingest_legal_records item failed source=% record=% err=%',
        source->>'slug',
        coalesce(item->'raw'->>'source_record_id', '?'),
        item_error;
      event_uuid := null;
      entity_uuid := null;
      raw_uuid := null;
    end;
  end loop;

  return jsonb_build_object(
    'source', source->>'slug',
    'fetched', jsonb_array_length(coalesce(records, '[]'::jsonb)),
    'inserted', inserted_count,
    'updated', updated_count,
    'skipped', skipped_count,
    'errors', error_count,
    'last_error', item_error
  );
end;
$function$
;

-- FUNCTION json_text_as_int
CREATE OR REPLACE FUNCTION public.json_text_as_int(input text, fallback integer)
 RETURNS integer
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
declare
  n numeric;
begin
  if input is null or btrim(input) = '' then
    return fallback;
  end if;
  begin
    n := input::numeric;
  exception when others then
    return fallback;
  end;
  if n is null then
    return fallback;
  end if;
  return round(n)::integer;
end;
$function$
;

-- FUNCTION normalize_entity_name
CREATE OR REPLACE FUNCTION public.normalize_entity_name(input text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select nullif(lower(trim(regexp_replace(coalesce(input, ''), '\s+', ' ', 'g'))), '');
$function$
;

-- FUNCTION prune_friction_score_history
CREATE OR REPLACE FUNCTION public.prune_friction_score_history(retention_days integer DEFAULT 365)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  deleted_count integer;
begin
  if retention_days is null or retention_days < 30 then
    retention_days := 30;
  end if;
  delete from public.friction_score_history
  where recorded_at < now() - make_interval(days => retention_days);
  get diagnostics deleted_count = row_count;
  return jsonb_build_object('table', 'friction_score_history', 'deleted', deleted_count, 'retention_days', retention_days);
end;
$function$
;

-- FUNCTION prune_query_audit_events
CREATE OR REPLACE FUNCTION public.prune_query_audit_events(retention_days integer DEFAULT 180)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  deleted_count integer;
begin
  if retention_days is null or retention_days < 30 then
    retention_days := 30;
  end if;
  delete from public.query_audit_events
  where created_at < now() - make_interval(days => retention_days);
  get diagnostics deleted_count = row_count;
  return jsonb_build_object('table', 'query_audit_events', 'deleted', deleted_count, 'retention_days', retention_days);
end;
$function$
;

-- FUNCTION refresh_map_cross_signals
CREATE OR REPLACE FUNCTION public.refresh_map_cross_signals()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
declare
  refreshed_count integer := 0;
begin
  delete from public.map_cross_signals;

  insert into public.map_cross_signals (
    id,
    trade_event_id,
    distress_event_id,
    trade_entity_id,
    distress_entity_id,
    correlation_key_type,
    ticker,
    trade_event_type,
    distress_event_type,
    trade_date,
    distress_date,
    days_between,
    longitude,
    latitude,
    location_confidence,
    location_precision,
    updated_at
  )
  with unique_tickers as (
    select
      upper(trim(ticker)) as ticker,
      (min(id::text))::uuid as issuer_entity_id
    from public.entities
    where ticker is not null
      and trim(ticker) <> ''
      and upper(trim(ticker)) <> 'NONE'
      and upper(trim(ticker)) ~ '^[A-Z][A-Z0-9.-]{0,7}$'
    group by upper(trim(ticker))
    having count(*) = 1
  ),
  trade_rows as (
    select
      trade_event.id,
      trade_event.entity_id,
      trade_event.event_type,
      coalesce(trade_event.trade_date, trade_event.filing_date) as event_date,
      upper(nullif(trim(trade_location.source_fields ->> 'ticker'), '')) as ticker,
      issuer.issuer_entity_id
    from public.legal_events trade_event
    join public.map_signal_locations trade_location
      on trade_location.event_id = trade_event.id
    join unique_tickers issuer
      on issuer.ticker = upper(nullif(trim(trade_location.source_fields ->> 'ticker'), ''))
    where
      (
        trade_event.event_type = 'form_4'
        and (
          trade_event.summary ~* 'Transaction code:\s*S(\.|$)'
          or trade_event.title ~* '\m(sale|sold|sell)\M'
        )
      )
      or (
        trade_event.event_type = 'congress_trade'
        and trade_location.source_fields ->> 'ticker' is not null
      )
  ),
  distress_rows as (
    select
      distress_event.id,
      distress_event.entity_id,
      distress_event.event_type,
      distress_event.filing_date as event_date,
      issuer.ticker,
      distress_location.longitude,
      distress_location.latitude,
      distress_location.geocoding_confidence,
      distress_location.location_precision
    from public.legal_events distress_event
    join public.map_signal_locations distress_location
      on distress_location.event_id = distress_event.id
    join public.entities distress_entity
      on distress_entity.id = distress_event.entity_id
    join unique_tickers issuer
      on issuer.issuer_entity_id = distress_entity.id
    where distress_event.event_type in (
      'warn_notice',
      'bankruptcy_chapter_11',
      'bankruptcy_chapter_7',
      'bankruptcy_docket',
      'bankruptcy_adversary'
    )
      and distress_location.geocoding_confidence <> 'unresolved'
      and distress_location.longitude is not null
      and distress_location.latitude is not null
  ),
  matched as (
    select
      trade.id as trade_event_id,
      distress.id as distress_event_id,
      trade.entity_id as trade_entity_id,
      distress.entity_id as distress_entity_id,
      'entity'::text as correlation_key_type,
      trade.ticker,
      trade.event_type as trade_event_type,
      distress.event_type as distress_event_type,
      trade.event_date as trade_date,
      distress.event_date as distress_date,
      (distress.event_date - trade.event_date)::integer as days_between,
      distress.longitude,
      distress.latitude,
      distress.geocoding_confidence as location_confidence,
      distress.location_precision
    from trade_rows trade
    join distress_rows distress
      on trade.issuer_entity_id = distress.entity_id
      and trade.ticker = distress.ticker
      and abs(distress.event_date - trade.event_date) <= 30
  )
  select
    (
      substr(md5(trade_event_id::text || ':' || distress_event_id::text), 1, 8)
      || '-' || substr(md5(trade_event_id::text || ':' || distress_event_id::text), 9, 4)
      || '-4' || substr(md5(trade_event_id::text || ':' || distress_event_id::text), 14, 3)
      || '-8' || substr(md5(trade_event_id::text || ':' || distress_event_id::text), 18, 3)
      || '-' || substr(md5(trade_event_id::text || ':' || distress_event_id::text), 21, 12)
    )::uuid,
    trade_event_id,
    distress_event_id,
    trade_entity_id,
    distress_entity_id,
    correlation_key_type,
    ticker,
    trade_event_type,
    distress_event_type,
    trade_date,
    distress_date,
    days_between,
    longitude,
    latitude,
    location_confidence,
    location_precision,
    now()
  from matched;

  get diagnostics refreshed_count = row_count;
  return refreshed_count;
end;
$function$
;

-- FUNCTION run_data_retention
CREATE OR REPLACE FUNCTION public.run_data_retention()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  return jsonb_build_object(
    'ok', true,
    'audit', public.prune_query_audit_events(180),
    'score_history', public.prune_friction_score_history(365),
    'ran_at', now()
  );
end;
$function$
;

-- FUNCTION set_updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

