#!/usr/bin/env node
/** Dump public schema DDL (tables, views, functions, indexes) into supabase/schema.sql */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { connectSupabasePg, projectRoot } from './lib/supabase-pg.mjs'

const root = projectRoot()
const outPath = resolve(root, 'supabase/schema.sql')

const { sql, host } = await connectSupabasePg()
try {
  console.log(`Dumping schema via ${host}…`)

  const tables = await sql`
    select c.relname as name, c.relkind
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind in ('r', 'v', 'm', 'p')
      and c.relname not like 'pg_%'
    order by c.relkind, c.relname
  `

  const columns = await sql`
    select table_name, column_name, data_type, udt_name, is_nullable, column_default, ordinal_position
    from information_schema.columns
    where table_schema = 'public'
    order by table_name, ordinal_position
  `

  const constraints = await sql`
    select
      tc.table_name,
      tc.constraint_name,
      tc.constraint_type,
      kcu.column_name,
      ccu.table_name as foreign_table_name,
      ccu.column_name as foreign_column_name
    from information_schema.table_constraints tc
    left join information_schema.key_column_usage kcu
      on tc.constraint_name = kcu.constraint_name and tc.table_schema = kcu.table_schema
    left join information_schema.constraint_column_usage ccu
      on ccu.constraint_name = tc.constraint_name and ccu.table_schema = tc.table_schema
    where tc.table_schema = 'public'
    order by tc.table_name, tc.constraint_name, kcu.ordinal_position
  `

  const indexes = await sql`
    select tablename, indexname, indexdef
    from pg_indexes
    where schemaname = 'public'
    order by tablename, indexname
  `

  const functions = await sql`
    select p.proname as name, pg_get_functiondef(p.oid) as def
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prokind in ('f', 'p')
    order by p.proname
  `

  const lines = []
  lines.push('-- Autogenerated dump of public schema (tables/views/indexes/functions).')
  lines.push(`-- Generated: ${new Date().toISOString()}`)
  lines.push('-- Source: live Supabase via scripts/dump-schema.mjs')
  lines.push('-- This file is documentation; apply changes via supabase/migrations/*.sql')
  lines.push('')

  lines.push('-- Objects')
  for (const t of tables) {
    const kind = t.relkind === 'r' ? 'TABLE' : t.relkind === 'v' ? 'VIEW' : t.relkind === 'm' ? 'MATERIALIZED VIEW' : 'PARTITIONED TABLE'
    lines.push(`-- ${kind} public.${t.name}`)
  }
  lines.push('')

  const byTable = new Map()
  for (const col of columns) {
    if (!byTable.has(col.table_name)) byTable.set(col.table_name, [])
    byTable.get(col.table_name).push(col)
  }

  for (const [table, cols] of byTable) {
    lines.push(`-- TABLE public.${table}`)
    lines.push(`-- create table public.${table} (`)
    for (const col of cols) {
      const typ = col.data_type === 'USER-DEFINED' ? col.udt_name : col.data_type
      const nulls = col.is_nullable === 'YES' ? 'null' : 'not null'
      const def = col.column_default ? ` default ${col.column_default}` : ''
      lines.push(`--   ${col.column_name} ${typ} ${nulls}${def},`)
    }
    lines.push('-- );')
    lines.push('')
  }

  lines.push('-- Constraints')
  for (const c of constraints) {
    lines.push(
      `-- ${c.constraint_type} ${c.table_name}.${c.constraint_name}` +
        (c.column_name ? ` (${c.column_name})` : '') +
        (c.foreign_table_name ? ` -> ${c.foreign_table_name}.${c.foreign_column_name}` : ''),
    )
  }
  lines.push('')

  lines.push('-- Indexes')
  for (const idx of indexes) {
    lines.push(`${idx.indexdef};`)
  }
  lines.push('')

  lines.push('-- Functions')
  for (const fn of functions) {
    lines.push(`-- FUNCTION ${fn.name}`)
    lines.push(fn.def + ';')
    lines.push('')
  }

  writeFileSync(outPath, lines.join('\n') + '\n', 'utf8')
  console.log(`Wrote ${outPath} (${tables.length} relations, ${indexes.length} indexes, ${functions.length} functions)`)
} finally {
  await sql.end({ timeout: 2 }).catch(() => undefined)
}
